version: "3"
services:
  redis:
    image: redis:latest
    container_name: "redis"
    command: redis-server --appendonly yes
    ports:
      - "6379"

  django_app:
    build: .
    container_name: django_app
    restart: always
    environment:
      - address=localhost
    expose:
      - 8000

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    depends_on:
      - django_app
    links:
      - django_app
    ports:
      - "80:80"
