version: "3"
services:
  redis:
    image: redis:latest
    container_name: "redis"
    expose:
      - 6379

  django_app:
    build: .
    container_name: hr_django
    restart: always
    expose:
      - 8000

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
