version: "3"
services:
  redis:
    image: redis:latest
    container_name: "redis"
    ports:
      - "6379"

  django_app:
    build: .
    container_name: hr_django
    restart: always
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "8000"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    depends_on:
      - django_app
    ports:
      - "80:80"
