version: "1.0"
services:
  redis:
    image: redis:latest
    container_name: "redis"
    expose:
      - 6379

  django_app:
    build: .
    container_name: hr_django
    restart: always
    ports:
      - 80:80
